version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  gem_cache:
  node_modules:
  bundle: